if(NOT MSVC AND NOT EMSCRIPTEN AND NOT APPLE)
  find_program(LLD_PATH NAMES ld.lld lld-20 lld-18 lld)
  if(LLD_PATH)
    add_link_options(-fuse-ld=lld)
    message(STATUS "Linker: lld (${LLD_PATH})")
  else()
    message(STATUS "Linker: lld not found, using default")
  endif()
endif()

find_program(CCACHE_PATH ccache)
if(CCACHE_PATH AND NOT CMAKE_CXX_COMPILER_LAUNCHER)
  set(CMAKE_C_COMPILER_LAUNCHER   "${CCACHE_PATH}" CACHE STRING "")
  set(CMAKE_CXX_COMPILER_LAUNCHER "${CCACHE_PATH}" CACHE STRING "")
  message(STATUS "Compiler cache: ccache (${CCACHE_PATH})")
endif()

option(GLVM_UNITY_BUILD "Enable unity builds" ON)
if(GLVM_UNITY_BUILD)
  message(STATUS "Unity build: ON")
endif()
